/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'gamesPlayed' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'avatarUrl' : IDL.Text,
});
export const GameType = IDL.Variant({
  'numberGuessing' : IDL.Null,
  'snake' : IDL.Null,
  'ticTacToe' : IDL.Null,
  'memoryCard' : IDL.Null,
});

export const idlService = IDL.Service({
  'addFriend' : IDL.Func([IDL.Principal], [], []),
  'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFriendsLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'recordGameResult' : IDL.Func([GameType, IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'gamesPlayed' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'avatarUrl' : IDL.Text,
  });
  const GameType = IDL.Variant({
    'numberGuessing' : IDL.Null,
    'snake' : IDL.Null,
    'ticTacToe' : IDL.Null,
    'memoryCard' : IDL.Null,
  });
  
  return IDL.Service({
    'addFriend' : IDL.Func([IDL.Principal], [], []),
    'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFriendsLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'recordGameResult' : IDL.Func([GameType, IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };